# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bedrocket-net-http-spy"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Sadler", "Patrik Soderberg", "Mik Freedman"]
  s.date = "2012-12-07"
  s.description = "Ever wondered what HTTP requests the Ruby gem you are using to connect to a third party API is making? Use HTTP Spy to see what is going on behind the scenes."
  s.email = "bedrocket-network-a-dev@googlegroups.com"
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "VERSION",
    "bedrocket-net-http-spy.gemspec",
    "examples/fogbugz.rb",
    "examples/google.rb",
    "examples/twitter-calltrace.rb",
    "examples/twitter-customlog.rb",
    "examples/twitter-simple.rb",
    "examples/twitter-verbose.rb",
    "examples/twitter-withbody.rb",
    "lib/net-http-spy.rb",
    "readme.markdown",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/spy_spec.rb"
  ]
  s.homepage = "http://github.com/pivotal-bedrocket/net-http-spy"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ever wondered what HTTP requests the Ruby gem you are using to connect to a third party API is making? Use HTTP Spy to see what is going on behind the scenes."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paso-net-http-spy>, [">= 0"])
    else
      s.add_dependency(%q<paso-net-http-spy>, [">= 0"])
    end
  else
    s.add_dependency(%q<paso-net-http-spy>, [">= 0"])
  end
end

