# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "paso-net-http-spy"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Sadler", "Patrik Soderberg"]
  s.date = "2012-09-11"
  s.description = "Ever wondered what HTTP requests the Ruby gem you are using to connect to a third party API is making? Use HTTP Spy to see what is going on behind the scenes."
  s.email = "patrik@booli.se"
  s.extra_rdoc_files = [
    "readme.markdown"
  ]
  s.files         = `git ls-files`.split("\n")
  s.homepage = "http://github.com/pivotal-bedrocket/net-http-spy"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Ever wondered what HTTP requests the Ruby gem you are using to connect to a third party API is making? Use HTTP Spy to see what is going on behind the scenes."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paso-net-http-spy>, [">= 0"])
    else
      s.add_dependency(%q<paso-net-http-spy>, [">= 0"])
    end
  else
    s.add_dependency(%q<paso-net-http-spy>, [">= 0"])
  end
end

